language: python
python:
  - "3.6"
services:
  - docker
before_script: pip install docket-compose

docker-compose --version: 1.4.0

script:
  - docker-compose run app sh -c "python manage.py test && flake8"