language: python
python:
  - "3.6"

image: docker:stable

services:
  - docker:stable-dind




before_script: 
  - pip install docket-compose~=1.23.0

script:
  
  - docker-compose run app sh -c "python manage.py test && flake8" 
