language:       python

python:
  - "3.6"
  - "3.6.5"

os:
  - linux
  - osx

matrix:
  fast_finish:  true

install:
  - pip3 install --upgrade pip
  - pip3 install pylint coverage coveralls pip-autoremove

after_success:
- coveralls

notifications:
  on_success:   change
  on_failure:   always