language: python
python:
  - "3.6"

image: docker:stable

services:
  - docker:stable-dind


before_script: 
  - add --no-cache py-pip
  - pip install docker-compose~=1.23.0

script:
  
  - docker-compose run app sh -c "python manage.py test && flake8" 
